FROM node:12.20.1
WORKDIR /app
COPY package*.json ./
ENV REACT_APP_API_HOST=http://localhost:8002
RUN npm install
COPY ./ ./
EXPOSE 3000
CMD ["npm","run","start"]


FROM node:12.20.1
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . /app
EXPOSE 4001
CMD ["node","app.js"]
